---
- name: Deploy configurations
  hosts: "{{ host | default('all') }}"
  user: "{{ deploy_user }}"
  become: true

  roles:
    - basic
    - security
    - dns
    - web
    - mail
    - shadowsocks

# vim: set ft=yaml sw=2: #
