---
- name: Deploy configurations
  hosts: "{{ host | default('all') }}"
  user: "{{ deploy_user }}"
  become: true

  roles:
    - role: basic
      tags: basic
    - role: security
      tags: security
    - role: dns
      tags: dns
    - role: web
      tags: web
    - role: mail
      tags: mail
    - role: shadowsocks
      tags: shadowsocks

# vim: set ft=yaml sw=2: #
