#!/bin/sh
#
# /usr/local/share/git-core/contrib/git-shell-commands/help
#
# Aaron LI
# 2017-06-18
#

if tty -s; then
    echo "Run 'help' for help, or 'exit' to leave.  Available commands:"
else
    echo "Run 'help' for help.  Available commands:"
fi

dir=$(dirname "$0")
cd "${dir}"

for cmd in *; do
    case "${cmd}" in
        help) ;;
        *.disabled) ;;
        *) [ -f "${cmd}" ] && [ -x "${cmd}" ] && echo "${cmd}" ;;
    esac
done
