---
- name: reload-opendkim
  command: rcreload milter-opendkim

- name: reload-postfix
  command: rcreload postfix

- name: reload-dovecot
  command: rcreload dovecot

- name: update-aliases
  command: postalias /etc/mail/aliases
