---
- name: reload-opendkim
  service:
    name: milter-opendkim
    state: reloaded

- name: reload-postfix
  service:
    name: postfix
    state: reloaded

- name: reload-dovecot
  service:
    name: dovecot
    state: reloaded

- name: update-aliases
  command: postalias /etc/mail/aliases
